/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import bus.DocGiaBUS;
import bus.MuonBUS;
import bus.SachBUS;
import dto.DocGiaDTO;
import dto.MuonDTO;
import dto.SachDTO;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itngu
 */
public final class ChoMuonSachJFrame extends javax.swing.JFrame {

    /**
     * Creates new form lapDocGiaJFrame
     */
    public ChoMuonSachJFrame() {
        initComponents();
        timKiemDocGia("", "", "", null, "");
        loadSachCoTheChoMuon("", "", "Y");
        loadDocGiaMuonSach();
    }
    
    public int timKiemDocGia(String ten, String cccd, String email, Date ngaySinh, String diachi){
        String[] header = {"CCCD", "Tên độc giả", "Địa chỉ", "Loại độc giả", "Email", "Ngày sinh", "Ngày lập thẻ",  "Ngày hết hạn"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header,0);
        ArrayList<DocGiaDTO> arr = DocGiaBUS.timDocGia(ten, cccd, email, ngaySinh, diachi);
        DocGiaDTO docgia;
        for(int i = 0; i < arr.size(); i++){
            docgia = arr.get(i);
            System.err.println("" + arr.get(i));
            String cccdRow =  docgia.getcCCD();
            String hotenRow = docgia.getTenDocGia();
            String diachiRow = docgia.getDiaChi();
            String loaiRow = docgia.getLoaiDocGia();
            String emailRow = docgia.getEmail();
            Date ngaySinhRow = docgia.getNgaySinh();
            Date ngayLapTheRow = docgia.getNgayLapThe();
            Date ngayHetHanRow = docgia.getNgayHetHan();
            Object[] row = { cccdRow, hotenRow, diachiRow, loaiRow, emailRow, ngaySinhRow, ngayLapTheRow, ngayHetHanRow};
            defaultTableModel.addRow(row);
        }
        jTableDocGia.setModel(defaultTableModel);        
        return arr.size();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtHoVaTenDocGia = new javax.swing.JTextField();
        jbtnXacNhanChoMuon = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jDtNgayHenTra = new com.toedter.calendar.JDateChooser();
        jDtNgayChoMuon = new com.toedter.calendar.JDateChooser();
        jtxtCCCD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtnTimKiem = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDocGia = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jtxtMaDocGia = new javax.swing.JTextField(20);
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblSachChoMuon = new javax.swing.JTable();
        jbtnTraCuuSachChoMuon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtTenSachTimKiem = new javax.swing.JTextField(20);
        jLabel5 = new javax.swing.JLabel();
        jtxtMaSachTimKiem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtTenSachChoMuon = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtMaSachChoMuon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblDocGiaDangMuon = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("CHO MƯỢN SÁCH");

        jLabel2.setText("Họ và tên ");

        jLabel6.setText("Ngày hẹn trả");

        jLabel7.setText("Ngày cho mượn");

        jtxtHoVaTenDocGia.setEditable(false);
        jtxtHoVaTenDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHoVaTenDocGiaActionPerformed(evt);
            }
        });

        jbtnXacNhanChoMuon.setText("Xác nhận cho mượn");
        jbtnXacNhanChoMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXacNhanChoMuonActionPerformed(evt);
            }
        });

        jbtnBack.setText("Trở về");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jDtNgayChoMuon.setDate(new java.util.Date());
        jDtNgayChoMuon.setEnabled(false);

        jtxtCCCD.setEditable(false);
        jtxtCCCD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCCCDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCCCDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCCCDKeyTyped(evt);
            }
        });

        jLabel8.setText("CCCD/CMND");

        jbtnTimKiem.setText("Tra cứu độc giả");
        jbtnTimKiem.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jbtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemActionPerformed(evt);
            }
        });

        jTableDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDocGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDocGia);

        jLabel9.setText("Thông tin độc giả");

        jtxtMaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaDocGiaActionPerformed(evt);
            }
        });

        jLabel11.setText("Mã độc giả");

        jButton1.setText("Nhập lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Thông tin sách");

        jTblSachChoMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sách", "Năm xuất bản", "Title 3", "Title 4"
            }
        ));
        jTblSachChoMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblSachChoMuonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblSachChoMuon);

        jbtnTraCuuSachChoMuon.setText("Tra cứu sách");
        jbtnTraCuuSachChoMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTraCuuSachChoMuonActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên sách");

        jLabel5.setText("Mã sách");

        jtxtMaSachTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaSachTimKiemActionPerformed(evt);
            }
        });

        jLabel10.setText("Tên sách cho mượn");

        jtxtTenSachChoMuon.setEnabled(false);

        jLabel12.setText("Mã sách cho mượn");

        jtxtMaSachChoMuon.setAutoscrolls(false);
        jtxtMaSachChoMuon.setEnabled(false);

        jLabel13.setText("Độc giả đang mượn");

        jTblDocGiaDangMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTblDocGiaDangMuon);

        jLabel14.setText("Danh sách độc giả ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtHoVaTenDocGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTenSachChoMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDtNgayHenTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMaSachChoMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDtNgayChoMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jbtnXacNhanChoMuon)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)
                        .addGap(480, 480, 480)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTenSachTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMaSachTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jbtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jbtnTraCuuSachChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtMaDocGia))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtxtTenSachTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTraCuuSachChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel10)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtMaSachTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jtxtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jtxtHoVaTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jtxtTenSachChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jtxtMaSachChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDtNgayChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDtNgayHenTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnXacNhanChoMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtHoVaTenDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHoVaTenDocGiaActionPerformed
    }//GEN-LAST:event_jtxtHoVaTenDocGiaActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ContainerJFrame form = new ContainerJFrame();
        form.pack();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jtxtCCCDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCCCDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCCCDKeyPressed

    private void jtxtCCCDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCCCDKeyTyped
        // TODO add your handling code here:       
    }//GEN-LAST:event_jtxtCCCDKeyTyped

    private void jtxtCCCDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCCCDKeyReleased
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jtxtCCCD.setText("");
        }
    }//GEN-LAST:event_jtxtCCCDKeyReleased

    private void jbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemActionPerformed
        // TODO add your handling code here:
        String maDocGia = jtxtMaDocGia.getText();
        int rs = 0;
        
        rs += timKiemDocGia("", maDocGia, "", null, "");
        if(rs == 0){
            JOptionPane.showMessageDialog(null, "Không tìm thấy!! Bạn hãy thử lại với thông tin khác xem! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Tìm thấy! " + rs + " kết quả", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_jbtnTimKiemActionPerformed

    private void jTableDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDocGiaMouseClicked
        // TODO add your handling code here:
        jtxtCCCD.setText(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 0).toString());
        jtxtHoVaTenDocGia.setText(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 1).toString());
        
    }//GEN-LAST:event_jTableDocGiaMouseClicked

    private void jbtnXacNhanChoMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXacNhanChoMuonActionPerformed
        
        if(jDtNgayHenTra.getDate()==null){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn ngày hẹn trả! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }else{
            if(jDtNgayHenTra.getDate().before(new java.util.Date())){
                JOptionPane.showMessageDialog(null, "Ngày hẹn trả phải sau ngày hôm nay! Kiểm tra lại ", "THÔNG BÁO",
                                    JOptionPane.WARNING_MESSAGE);
            }
        }
        
        if(jtxtCCCD.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn phải chọn độc giả trước khi cho mượn! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }
        
        if(jtxtMaSachChoMuon.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn phải chọn sách để cho mượn! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }
                
        if(jDtNgayChoMuon.getDate()==null){
            JOptionPane.showMessageDialog(null, "Kiểm tra lại ngày cho mượn! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }
        
        if(jDtNgayHenTra.getDate()!=null && jDtNgayHenTra.getDate().after(new java.util.Date()) && !jtxtCCCD.getText().isEmpty() && jDtNgayChoMuon.getDate()!=null && !jtxtMaSachChoMuon.getText().isEmpty()){
            try {
                String maDocGia = jtxtCCCD.getText();
                String maSachChoMuon = jtxtMaSachChoMuon.getText();              
                Date ngayHenTra = jDtNgayHenTra.getDate();
                Date ngayChoMuon = jDtNgayChoMuon.getDate();    
                MuonDTO obj = new MuonDTO();
                obj.setMadocgia(maDocGia);
                obj.setMasach(maSachChoMuon);
                obj.setNgaychomuon(ngayChoMuon);
                obj.setNgayhentra(ngayHenTra);
                
                int i = MuonBUS.choMuonSach(obj);

                switch (i) {
                    case 0:
                        JOptionPane.showMessageDialog(null, " Lỗi ! Vui lòng liên hệ admin! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    case -1:
                        JOptionPane.showMessageDialog(null, "Sách đã có người khác mượn! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    case -2:
                        JOptionPane.showMessageDialog(null, "Thẻ hết hạn! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    case -3:
                        JOptionPane.showMessageDialog(null, "Độc giả này mượn không thể mượn thêm!! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    case -4:
                        JOptionPane.showMessageDialog(null, "Chỉ có thể mượn sách theo số ngày quy định của thư viện!! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Cho mượn thành công! ", "THÀNH CÔNG",
                            JOptionPane.WARNING_MESSAGE);
                        break;
                }
                
            } catch (Exception ex) {
                Logger.getLogger(ChoMuonSachJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            reset();
            
            loadSachCoTheChoMuon("", "", "Y");
            loadDocGiaMuonSach();
        }        
        
    }//GEN-LAST:event_jbtnXacNhanChoMuonActionPerformed

    private void reset(){
        jtxtCCCD.setText("");
        jtxtHoVaTenDocGia.setText("");
        jtxtTenSachChoMuon.setText("");
        jtxtMaSachChoMuon.setText("");
        //jDtNgayChoMuon.setDate(null);
        jDtNgayHenTra.setDate(null);
        jTableDocGia.clearSelection();
        jTblSachChoMuon.clearSelection();
    }
    private void jtxtMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaDocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMaDocGiaActionPerformed
   

    private void jbtnTraCuuSachChoMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTraCuuSachChoMuonActionPerformed
        // TODO add your handling code here:
        String tenSach = "";
        if (jtxtTenSachTimKiem.getText().isEmpty()) {
            tenSach += tenSach;
        }else{            
            tenSach += jtxtTenSachTimKiem.getText();
        }        
        
        String maSach= "";
        if (jtxtMaSachTimKiem.getText().isEmpty()) {
            maSach += maSach;
        }else{            
            maSach += jtxtMaSachTimKiem.getText();
        }    
        int i = loadSachCoTheChoMuon(maSach, tenSach, "Y");
        if(i==0){
            JOptionPane.showMessageDialog(null, "Không tìm thấy!! Bạn hãy thử lại với thông tin khác xem! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Tìm thấy! " + i + " cuốn sách", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jbtnTraCuuSachChoMuonActionPerformed

    private void jTblSachChoMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblSachChoMuonMouseClicked
        // TODO add your handling code here:
        jtxtMaSachChoMuon.setText(jTblSachChoMuon.getValueAt(jTblSachChoMuon.getSelectedRow(), 0).toString());
        jtxtTenSachChoMuon.setText(jTblSachChoMuon.getValueAt(jTblSachChoMuon.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jTblSachChoMuonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtMaSachTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaSachTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMaSachTimKiemActionPerformed
    
    public int loadSachCoTheChoMuon(String ISBN, String tenSach, String flag){
        String[] header = {"ISBN", "Tên sách", "Tác giả", "Thể loại"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header,0);
        ArrayList<SachDTO> arr = SachBUS.loadSachCoTheChoMuon(ISBN, tenSach, flag);
        SachDTO sach;
        for(int i = 0; i < arr.size(); i++){
            sach = arr.get(i);
            String isbn =  sach.getISBN();
            String ten_sach = sach.getTenSach();
            String the_loai = sach.getTheLoaiSach();
            String tac_gia = sach.getTacGia();
            Object[] row = { isbn, ten_sach, tac_gia, the_loai};
            defaultTableModel.addRow(row);
        }            
        jTblSachChoMuon.setModel(defaultTableModel);            
        return arr.size();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoMuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoMuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoMuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoMuonSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoMuonSachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDtNgayChoMuon;
    private com.toedter.calendar.JDateChooser jDtNgayHenTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDocGia;
    private javax.swing.JTable jTblDocGiaDangMuon;
    private javax.swing.JTable jTblSachChoMuon;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JToggleButton jbtnTimKiem;
    private javax.swing.JButton jbtnTraCuuSachChoMuon;
    private javax.swing.JButton jbtnXacNhanChoMuon;
    private javax.swing.JTextField jtxtCCCD;
    private javax.swing.JTextField jtxtHoVaTenDocGia;
    private javax.swing.JTextField jtxtMaDocGia;
    private javax.swing.JTextField jtxtMaSachChoMuon;
    private javax.swing.JTextField jtxtMaSachTimKiem;
    private javax.swing.JTextField jtxtTenSachChoMuon;
    private javax.swing.JTextField jtxtTenSachTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadDocGiaMuonSach() {
        String[] header = {"Mã độc giả", "Tên độc giả", "Tên sách", "Ngày hẹn trả"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header,0);
        ArrayList<MuonDTO> arr = MuonBUS.loadDocGiaMuonSach();
        MuonDTO dto;
        for(int i = 0; i < arr.size(); i++){
            dto = arr.get(i);
            String madocgia =  dto.getMadocgia();
            String ten_sach = dto.getTensach();
            String tendocgia = dto.getTendocgia();
            Date ngayhentra = dto.getNgayhentra();
            Object[] row = { madocgia, tendocgia, ten_sach, ngayhentra};
            defaultTableModel.addRow(row);
        }            
        jTblDocGiaDangMuon.setModel(defaultTableModel);
        
    }

    
}
