/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import bus.DocGiaBUS;
import dto.DocGiaDTO;
import function.EmailValidate;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;  
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itngu
 */
public final class LapTheDocGiaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form lapDocGiaJFrame
     */
    public LapTheDocGiaJFrame() {
        initComponents();
        timKiemDocGia("", "", "", null, "");
    }
    
    public int timKiemDocGia(String ten, String cccd, String email, Date ngaySinh, String diachi){

        String[] header = {"CCCD", "Tên độc giả", "Địa chỉ", "Loại độc giả", "Email", "Ngày sinh", "Ngày lập thẻ",  "Ngày hết hạn"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header,0);
        ArrayList<DocGiaDTO> arr = DocGiaBUS.timDocGia(ten, cccd, email, ngaySinh, diachi);
        DocGiaDTO docgia;
        for(int i = 0; i < arr.size(); i++){
            docgia = arr.get(i);            
            String cccdRow =  docgia.getcCCD();
            String hotenRow = docgia.getTenDocGia();
            String diachiRow = docgia.getDiaChi();
            String loaiRow = docgia.getLoaiDocGia();
            String emailRow = docgia.getEmail();
            Date ngaySinhRow = docgia.getNgaySinh();
            Date ngayLapTheRow = docgia.getNgayLapThe();
            Date ngayHetHanRow = docgia.getNgayHetHan();
            Object[] row = { cccdRow, hotenRow, diachiRow, loaiRow, emailRow, ngaySinhRow, ngayLapTheRow, ngayHetHanRow};
            defaultTableModel.addRow(row);
        }         

        jTableDocGia.setModel(defaultTableModel);        
        return arr.size();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtHoVaTenDocGia = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtDiaChi = new javax.swing.JTextField();
        jRadX = new javax.swing.JRadioButton();
        jRadY = new javax.swing.JRadioButton();
        jbtnXacNhanLapTheDocGia = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jDtNgaySinh = new com.toedter.calendar.JDateChooser();
        jDtNgayLapThe = new com.toedter.calendar.JDateChooser();
        jtxtCCCD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtnCapNhat = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();
        jbtnTimKiem = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDocGia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText(" THẺ ĐỘC GIẢ");

        jLabel2.setText("Họ và tên ");

        jLabel3.setText("Địa chỉ");

        jLabel4.setText("Loại độc giả");

        jLabel5.setText("e-mail");

        jLabel6.setText("Ngày Sinh");

        jLabel7.setText("Ngày lập thẻ");

        buttonGroup1.add(jRadX);
        jRadX.setText("X");

        buttonGroup1.add(jRadY);
        jRadY.setText("Y");

        jbtnXacNhanLapTheDocGia.setText("Xác nhận thêm");
        jbtnXacNhanLapTheDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXacNhanLapTheDocGiaActionPerformed(evt);
            }
        });

        jbtnBack.setText("Trở về");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jDtNgayLapThe.setDate(new java.util.Date());
        jDtNgayLapThe.setEnabled(false);

        jLabel8.setText("CCCD/CMND");

        jbtnCapNhat.setText("Cập nhật");
        jbtnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCapNhatActionPerformed(evt);
            }
        });

        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        jbtnTimKiem.setText("Tìm kiếm");
        jbtnTimKiem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemActionPerformed(evt);
            }
        });

        jTableDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4",  "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableDocGia.setGridColor(new java.awt.Color(255, 204, 255));
        jTableDocGia.setInheritsPopupMenu(true);
        jTableDocGia.setName(""); // NOI18N
        jTableDocGia.setSelectionBackground(new java.awt.Color(0, 153, 0));
        jTableDocGia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDocGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDocGia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnXacNhanLapTheDocGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(135, 135, 135)
                                .addComponent(jRadX)
                                .addGap(74, 74, 74)
                                .addComponent(jRadY)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabel8))
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDtNgayLapThe, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtHoVaTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jbtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8))
                    .addComponent(jtxtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jtxtHoVaTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jtxtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDtNgayLapThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(jRadX)
                    .addComponent(jRadY))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnXacNhanLapTheDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnXacNhanLapTheDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXacNhanLapTheDocGiaActionPerformed
       
        EmailValidate emailValidate = new EmailValidate();        
        if(jtxtCCCD.getText().isEmpty() || jtxtCCCD.getText().length() > 12 || jtxtCCCD.getText().length() < 9){
            JOptionPane.showMessageDialog(null, "Căn cước công dân không hợp lệ!", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jtxtCCCD.requestFocus();                
        }else if(jtxtHoVaTenDocGia.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên độc giả", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jtxtHoVaTenDocGia.requestFocus();
        }else if(jDtNgaySinh.getDate() == null){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày sinh độc giả", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jDtNgayLapThe.requestFocus();
        }else if(!emailValidate.validate(jtxtEmail.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Email không hợp lệ!", "THÔNG BÁO",
                             JOptionPane.WARNING_MESSAGE);
            jtxtEmail.requestFocus();                
        } 
        else if(!jRadX.isSelected() && !jRadY.isSelected()){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn loại độc giả", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jRadX.setBackground(Color.red);
            jRadY.setBackground(Color.red);
        }else{
            try {
                String rad ="" ;
                if(jRadX.isSelected()){
                    rad += jRadX.getText();
                }
                if(jRadY.isSelected()){
                    rad += jRadY.getText();
                }
                
                java.sql.Date ngaySinh = new java.sql.Date(jDtNgaySinh.getDate().getTime());
                java.sql.Date ngayLapThe = new java.sql.Date(jDtNgayLapThe.getDate().getTime());
                
                DocGiaDTO docgia = new DocGiaDTO();
                docgia.setcCCD(jtxtCCCD.getText());
                docgia.setTenDocGia(jtxtHoVaTenDocGia.getText());
                docgia.setDiaChi(jtxtDiaChi.getText());
                docgia.setEmail(jtxtEmail.getText());
                docgia.setLoaiDocGia(rad);
                docgia.setNgayLapThe(ngayLapThe);
                docgia.setNgaySinh(ngaySinh);
                
                int  i = DocGiaBUS.themDocGia(docgia);               
                
                switch (i) {
                    case 0:
                        JOptionPane.showMessageDialog(null, "Đã tồn tại mã độc giả ", "THẤT BẠI",
                                JOptionPane.ERROR_MESSAGE);
                        break; 
                    case -1:
                        JOptionPane.showMessageDialog(null, "Tuổi không hợp lệ! Kiểm tra lại ngày sinh!!!", "THẤT BẠI",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    case 1:
                        JOptionPane.showMessageDialog(null, "Tạo thẻ độc giả thành công", "THÀNH CÔNG", JOptionPane.INFORMATION_MESSAGE);
                        break;
                }
            } catch (Exception ex) {
                Logger.getLogger(LapTheDocGiaJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        timKiemDocGia("", "", "", null, "");
        
    }//GEN-LAST:event_jbtnXacNhanLapTheDocGiaActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ContainerJFrame form = new ContainerJFrame();
        form.pack();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCapNhatActionPerformed
        // TODO add your handling code here:
        if(jTableDocGia.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Hãy chọn độc giả để cập nhật hoặc là tìm kiếm!", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);            
        }else if(jtxtCCCD.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn muốn cập nhật thông tin của độc giả nào???", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jtxtCCCD.requestFocus();   
        }else if(jtxtCCCD.getText().length() > 12 || jtxtCCCD.getText().length() < 9){
            JOptionPane.showMessageDialog(null, "Căn cước công dân không hợp lệ!", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jtxtCCCD.requestFocus();
        }else if(jDtNgaySinh.getDate() == null){
            JOptionPane.showMessageDialog(null, "Ngày sinh không được để trống!", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jDtNgayLapThe.requestFocus(); 
        }else if(!jRadX.isSelected() && !jRadY.isSelected()){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn loại độc giả", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
            jRadX.setBackground(Color.red);
            jRadY.setBackground(Color.red);
        }else{
            
            String rad ="" ;
            if(jRadX.isSelected()){
                rad += jRadX.getText();
            }
            if(jRadY.isSelected()){
                rad += jRadY.getText();
            }

            java.sql.Date ngaySinh = new java.sql.Date(jDtNgaySinh.getDate().getTime());
            java.sql.Date ngayLapThe = new java.sql.Date(jDtNgayLapThe.getDate().getTime());            
            
            String oldCCCD = jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 0).toString();
            DocGiaDTO docgia = new DocGiaDTO();
            docgia.setcCCD(jtxtCCCD.getText());
            docgia.setTenDocGia(jtxtHoVaTenDocGia.getText());
            docgia.setDiaChi(jtxtDiaChi.getText());
            docgia.setEmail(jtxtEmail.getText());
            docgia.setLoaiDocGia(rad);
            docgia.setNgayLapThe(ngayLapThe);
            docgia.setNgaySinh(ngaySinh);
            
            try {                 
                int  i = DocGiaBUS.capNhatDocGia(oldCCCD, docgia);
                switch (i) {
                    case -1:
                        JOptionPane.showMessageDialog(null, "Tuổi không hợp lệ! Kiểm tra lại ngày sinh!!!", "THẤT BẠI",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    case 1:
                        JOptionPane.showMessageDialog(null, "Cập nhật thông tin độc giả thành công", "THÀNH CÔNG", JOptionPane.INFORMATION_MESSAGE);
                        break;
                }
            } catch (Exception ex) {
                Logger.getLogger(LapTheDocGiaJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            timKiemDocGia("", "", "", null, "");    
        }
        
    }//GEN-LAST:event_jbtnCapNhatActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        // TODO add your handling code here:
        ArrayList<String> arr = new ArrayList<String>();
        
        if(jTableDocGia.getSelectedRow()> -1){
            int[] selectedrows  = jTableDocGia.getSelectedRows();
            for (int i = 0; i < selectedrows.length; i++){
                arr.add(jTableDocGia.getValueAt(selectedrows[i], 0).toString());
            }
        }
        
        try {
            int i = DocGiaBUS.Xoa(arr);
            if(i>0){
                JOptionPane.showMessageDialog(null, "Xóa thành công " +i + " độc giả" , "THÀNH CÔNG", JOptionPane.INFORMATION_MESSAGE);                        
            }
        } catch (Exception ex) {
            Logger.getLogger(LapTheDocGiaJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }        
        timKiemDocGia("", "", "", null, "");  
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemActionPerformed
        // TODO add your handling code here:
        String cccd = jtxtCCCD.getText();
        String ten = jtxtHoVaTenDocGia.getText();
        String email = jtxtEmail.getText();
        Date ngaySinh = jDtNgaySinh.getDate();
        String diachi = jtxtDiaChi.getText();
        
        int rs = timKiemDocGia(ten, cccd, email, ngaySinh, diachi);
        if(rs == 0){
            JOptionPane.showMessageDialog(null, "Không tìm thấy!! Bạn hãy thử lại với thông tin khác xem! ", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Tìm thấy! " + rs + " kết quả", "THÔNG BÁO",
                                JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_jbtnTimKiemActionPerformed

    private void jTableDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDocGiaMouseClicked
        // TODO add your handling code here:
        jtxtCCCD.setText(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 0).toString());
        jtxtHoVaTenDocGia.setText(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 1).toString());
        jtxtDiaChi.setText(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 2).toString());
        if("X".equals(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 3).toString())){
            jRadX.setSelected(true);
        }
        if("Y".equals(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 3).toString())){
            jRadY.setSelected(true);
        }
        jtxtEmail.setText(jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 4).toString());
        jDtNgaySinh.setDate((Date) jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 5));
        jDtNgayLapThe.setDate((Date) jTableDocGia.getValueAt(jTableDocGia.getSelectedRow(), 6));
                
        
    }//GEN-LAST:event_jTableDocGiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGiaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGiaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGiaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGiaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapTheDocGiaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDtNgayLapThe;
    private com.toedter.calendar.JDateChooser jDtNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadX;
    private javax.swing.JRadioButton jRadY;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDocGia;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnCapNhat;
    private javax.swing.JToggleButton jbtnTimKiem;
    private javax.swing.JButton jbtnXacNhanLapTheDocGia;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JTextField jtxtCCCD;
    private javax.swing.JTextField jtxtDiaChi;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtHoVaTenDocGia;
    // End of variables declaration//GEN-END:variables
}
