/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import bus.QuyDinhBUS;
import bus.SachBUS;
import dto.QuyDinhDTO;
import dto.SachDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author itngu
 */
public final class ThemSachJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThemSachJFrame
     */
    public ThemSachJFrame() {
        initComponents();
        loadTheLoaiSachs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTheLoaiSach = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtxtISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTenSach = new javax.swing.JTextField();
        jRadA = new javax.swing.JRadioButton();
        jRadB = new javax.swing.JRadioButton();
        jRadC = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jYear = new com.toedter.calendar.JYearChooser();
        jLabel5 = new javax.swing.JLabel();
        jDtNgayNhapSach = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jbtnThemSach = new javax.swing.JToggleButton();
        jtxtNhaXuatBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtTenTacGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaTinhTrangSach = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sách (ISBN)");

        jLabel2.setText("THÊM SÁCH");

        jLabel3.setText("Tên sách");

        btnGroupTheLoaiSach.add(jRadA);
        jRadA.setText("A");

        btnGroupTheLoaiSach.add(jRadB);
        jRadB.setText("B");

        btnGroupTheLoaiSach.add(jRadC);
        jRadC.setText("C");

        jLabel4.setText("Thể loại sách");

        jLabel5.setText("Năm xuất bản");

        jDtNgayNhapSach.setDate(new java.util.Date());

        jLabel6.setText("Ngày nhập");

        jbtnThemSach.setText("Thêm Sách");
        jbtnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemSachActionPerformed(evt);
            }
        });

        jLabel7.setText("Nhà xuất bản");

        jLabel8.setText("Tên tác giả");

        jtxtAreaTinhTrangSach.setColumns(20);
        jtxtAreaTinhTrangSach.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaTinhTrangSach);

        jLabel9.setText("Ghi chú");

        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát ứng dụng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDtNgayNhapSach, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jbtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadA)
                            .addComponent(jRadB)
                            .addComponent(jRadC)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDtNgayNhapSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void loadTheLoaiSachs() {
        ArrayList<QuyDinhDTO>  arr = QuyDinhBUS.loadTheLoaiSach();
        QuyDinhDTO dto;
        for (int i = 0; i < arr.size(); i++){
            dto = arr.get(i);
            String theLoaiA = dto.getQD_theloaisach1();
            String theLoaiB = dto.getQD_theloaisach2();
            String theLoaiC = dto.getQD_theloaisach3();
            jRadA.setText(theLoaiA);
            jRadB.setText(theLoaiB);
            jRadC.setText(theLoaiC);
        }   
        
    }
    
    private void jbtnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemSachActionPerformed
        // TODO add your handling code here:
        String rad ="" ;
        if(jRadA.isSelected()){
            rad += jRadA.getText();
        }
        if(jRadB.isSelected()){
            rad += jRadB.getText();
        }
        if(jRadC.isSelected()){
            rad += jRadC.getText();
        }      
        
        if(jtxtISBN.getText().length() > 12 || jtxtISBN.getText().length() < 9){
            JOptionPane.showMessageDialog(null, "Mã sách từ 10~11 kí tự!" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
            jtxtISBN.requestFocus();
        }else if(jtxtISBN.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã sách" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
            jtxtISBN.requestFocus();
        }else if(jtxtTenSach.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên sách" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
            jtxtTenSach.requestFocus();
        }else if(jtxtTenTacGia.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên tác giả" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);            
            jtxtTenTacGia.requestFocus();
        }else if(jDtNgayNhapSach.getDate() == null){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày sinh độc giả" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
            jDtNgayNhapSach.requestFocus();
        }else if(jYear.getYear() < 0 || jYear.toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập năm xuất bản" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
            jYear.requestFocus();
        }else if(rad.isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn thể loại sách" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
            jRadA.setBackground(Color.red);
            jRadB.setBackground(Color.red);
            jRadC.setBackground(Color.red);
        } else if(jtxtNhaXuatBan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập nhà xuất bản" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
            jtxtNhaXuatBan.requestFocus();
        }else{                
            try {
                String isbn = jtxtISBN.getText();                
                String tenSach = jtxtTenSach.getText();
                String tenTacGia = jtxtTenTacGia.getText();
                String nhaXuatBan = jtxtNhaXuatBan.getText();
                String tinhTrang = jtxtAreaTinhTrangSach.getText();
                Integer year = jYear.getYear();
                Date ngayNhap = new java.sql.Date(jDtNgayNhapSach.getDate().getTime());
                
                // Kiểm tra có mã sách này chưa~!
                int i = SachBUS.timKiemSach(isbn, "", "", "", null, null, "").size();
                if(i>0){
                    JOptionPane.showMessageDialog(null, "Mã sách này đã tồn tại" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    SachDTO sach = new SachDTO();
                    sach.setISBN(isbn);
                    sach.setTenSach(tenSach);
                    sach.setNamXuatBan(year);
                    sach.setNgayNhap(ngayNhap);
                    sach.setNhaXuatBan(nhaXuatBan);
                    sach.setTacGia(tenTacGia);
                    sach.setTheLoaiSach(rad);
                    sach.setTinhTrangSach(tinhTrang);

                    int j = SachBUS.themSach(sach);
                    if (j == 0) {
                        JOptionPane.showMessageDialog(null, "Thêm sách thất bại" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, "Thêm thành công" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);
                        jtxtTenSach.setText("");
                        jtxtISBN.setText("");
                        jtxtNhaXuatBan.setText("");
                        jtxtAreaTinhTrangSach.setText("");
                        jtxtTenTacGia.setText("");
                    }
                }                
                
            } catch (Exception ex) {
                Logger.getLogger(ThemSachJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnThemSachActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            this.dispose();
            TimKiemSachJFrame frm = new TimKiemSachJFrame();
            frm.pack();
            frm.setVisible(true);
            frm.setLocationRelativeTo(null);
        } catch (Exception ex) {
            Logger.getLogger(ThemSachJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Thoát?", "Bạn có chắc muốn thoát?", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION){
            System.exit(0);
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTheLoaiSach;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDtNgayNhapSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadA;
    private javax.swing.JRadioButton jRadB;
    private javax.swing.JRadioButton jRadC;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jYear;
    private javax.swing.JToggleButton jbtnThemSach;
    private javax.swing.JTextArea jtxtAreaTinhTrangSach;
    private javax.swing.JTextField jtxtISBN;
    private javax.swing.JTextField jtxtNhaXuatBan;
    private javax.swing.JTextField jtxtTenSach;
    private javax.swing.JTextField jtxtTenTacGia;
    // End of variables declaration//GEN-END:variables
  
   
}


