/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import bus.QuyDinhBUS;
import bus.SachBUS;
import dto.QuyDinhDTO;
import dto.SachDTO;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itngu
 */
public final class TimKiemSachJFrame extends javax.swing.JFrame {

    /**
     * Creates new form sachJFrame
     */
    public TimKiemSachJFrame(){
        initComponents();        
        loadTheLoaiSachs();
        timKiemSach("", "", "", "", null, null, "");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTheLoaiSach = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTenTacGia = new javax.swing.JTextField();
        jbtnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSach = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jtxtTenSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadA = new javax.swing.JRadioButton();
        jRadB = new javax.swing.JRadioButton();
        jRadC = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tìm kiếm sách");

        jLabel2.setText("Nhập thông tin tìm kiếm");

        jbtnTimKiem.setText("Tìm kiếm sách");
        jbtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemActionPerformed(evt);
            }
        });

        jTblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sách", "Năm xuất bản", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblSach);

        jToggleButton1.setText("Thêm sách mới");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên sách");

        jLabel4.setText("Tên tác giả");

        buttonGroupTheLoaiSach.add(jRadA);
        jRadA.setText("A");

        buttonGroupTheLoaiSach.add(jRadB);
        jRadB.setText("B");
        jRadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBActionPerformed(evt);
            }
        });

        buttonGroupTheLoaiSach.add(jRadC);
        jRadC.setText("C");

        jLabel5.setText("Thể loại sách");

        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtTenSach)
                                .addComponent(jtxtTenTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadA)
                                .addGap(18, 18, 18)
                                .addComponent(jRadB)
                                .addGap(31, 31, 31)
                                .addComponent(jRadC)))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadA)
                    .addComponent(jRadB)
                    .addComponent(jRadC)
                    .addComponent(jLabel5)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemActionPerformed
        
        String rad ="" ;
        if(jRadA.isSelected()){
            rad += jRadA.getText();
        }
        if(jRadB.isSelected()){
            rad += jRadB.getText();
        }
        if(jRadC.isSelected()){
            rad += jRadC.getText();
        }

        if(jtxtTenTacGia.getText().isEmpty() && jtxtTenSach.getText().isEmpty() && rad.isEmpty() ){
            //JOptionPane.showMessageDialog(null, "Hãy nhập một vài thông tin để tìm kiếm" , "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE); 
            //jtxtTenTacGia.requestFocus();
            int i = timKiemSach("", "", "", "", null, null, "");
            if(i > 0){
                JOptionPane.showMessageDialog(null, "Tìm thấy " +i + " quyển sách" , "THÀNH CÔNG", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Không tìm thấy sách!" , "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{            
            String tenTacGia = jtxtTenTacGia.getText();
            String tenSach = jtxtTenSach.getText();  
            int i = timKiemSach("", tenSach, tenTacGia, rad, null, null, "");
            if(i > 0){
                JOptionPane.showMessageDialog(null, "Tìm thấy " +i + " quyển sách" , "THÀNH CÔNG", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Không tìm thấy sách!" , "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtnTimKiemActionPerformed
    
    private void loadTheLoaiSachs() {
        ArrayList<QuyDinhDTO>  arr = QuyDinhBUS.loadTheLoaiSach();
        QuyDinhDTO dto;
        for (int i = 0; i < arr.size(); i++){
            dto = arr.get(i);
            String theLoaiA = dto.getQD_theloaisach1();
            String theLoaiB = dto.getQD_theloaisach2();
            String theLoaiC = dto.getQD_theloaisach3();
            jRadA.setText(theLoaiA);
            jRadB.setText(theLoaiB);
            jRadC.setText(theLoaiC);
        }   
        
    }
    
    public int timKiemSach(String ISBN, String tenSach, String tenTacGia, String theLoai, Date ngayNhap, Integer namXuatBan, String nhaXuatBan){
        String[] header = {"ISBN", "Tên sách", "Tác giả", "Thể loại", "Ngày nhập", "Năm xuất bản", "Nhà xuất bản" };
        DefaultTableModel defaultTableModel = new DefaultTableModel(header,0);
        ArrayList<SachDTO> arr = SachBUS.timKiemSach(ISBN, tenSach, tenTacGia, theLoai, ngayNhap, namXuatBan, nhaXuatBan);
        SachDTO sach;
        for(int i = 0; i < arr.size(); i++){
            sach = arr.get(i);
            String isbn =  sach.getISBN();
            String ten_sach = sach.getTenSach();
            String the_loai = sach.getTheLoaiSach();
            String tac_gia = sach.getTacGia();
            Date ngay_nhap = sach.getNgayNhap();
            int nam_xuat_ban = sach.getNamXuatBan();
            String nha_xuat_ban = sach.getNhaXuatBan();
            Object[] row = { isbn, ten_sach, tac_gia, the_loai, ngay_nhap, nam_xuat_ban, nha_xuat_ban};
            defaultTableModel.addRow(row);
        }            
        jTblSach.setModel(defaultTableModel);            
        return arr.size();
    }
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ThemSachJFrame form = new ThemSachJFrame();
        form.pack();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jRadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        ContainerJFrame form = new ContainerJFrame();
        form.pack();
        form.setVisible(true);
        form.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TimKiemSachJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TimKiemSachJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTheLoaiSach;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadA;
    private javax.swing.JRadioButton jRadB;
    private javax.swing.JRadioButton jRadC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblSach;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbtnTimKiem;
    private javax.swing.JTextField jtxtTenSach;
    private javax.swing.JTextField jtxtTenTacGia;
    // End of variables declaration//GEN-END:variables

    
  
}
