/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import bus.MuonBUS;
import dto.MuonDTO;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author itngu
 */
public class TraSachJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TraSachJFrame
     */
    public TraSachJFrame() {
        initComponents();
        loadDocGiaMuonSach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTblDocGiaDangMuon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jbtnXacNhanTra = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jtxtMaSach = new javax.swing.JTextField(20);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTblDocGiaDangMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblDocGiaDangMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblDocGiaDangMuonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTblDocGiaDangMuon);

        jLabel2.setText("Mã sách");

        jbtnXacNhanTra.setText("Xác nhận trả");
        jbtnXacNhanTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXacNhanTraActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Trở về");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("TRẢ SÁCH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnXacNhanTra)
                                .addGap(77, 77, 77)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnXacNhanTra)
                    .addComponent(jToggleButton2))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ContainerJFrame form = new ContainerJFrame();
        form.pack();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jbtnXacNhanTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXacNhanTraActionPerformed
        // TODO add your handling code here:
        String maSach = jtxtMaSach.getText();
        int i =0;
        i += MuonBUS.traSach(maSach);
        if(i>0){
            JOptionPane.showMessageDialog(null, "Đã ghi nhận trả sách" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);    
        }else{
            JOptionPane.showMessageDialog(null, "Kiểm tra lại mã sách" , "THÔNG BÁO!", JOptionPane.INFORMATION_MESSAGE);    
        }
        
        loadDocGiaMuonSach();
    }//GEN-LAST:event_jbtnXacNhanTraActionPerformed

    private void jTblDocGiaDangMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblDocGiaDangMuonMouseClicked
        jtxtMaSach.setText(jTblDocGiaDangMuon.getValueAt(jTblDocGiaDangMuon.getSelectedRow(), 2).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTblDocGiaDangMuonMouseClicked

    private void loadDocGiaMuonSach() {
        String[] header = {"Mã độc giả", "Tên độc giả", "Tên sách", "Ngày hẹn trả"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(header,0);
        ArrayList<MuonDTO> arr = MuonBUS.loadDocGiaMuonSach();
        MuonDTO dto;
        for(int i = 0; i < arr.size(); i++){
            dto = arr.get(i);
            String madocgia =  dto.getMadocgia();
            String masach = dto.getMasach();
            String tendocgia = dto.getTendocgia();
            Date ngayhentra = dto.getNgayhentra();
            Object[] row = { madocgia, tendocgia, masach, ngayhentra};
            defaultTableModel.addRow(row);
        }            
        jTblDocGiaDangMuon.setModel(defaultTableModel);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraSachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraSachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblDocGiaDangMuon;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jbtnXacNhanTra;
    private javax.swing.JTextField jtxtMaSach;
    // End of variables declaration//GEN-END:variables
}
